# Generated by Django 5.1 on 2024-08-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actor",
            name="plays",
        ),
        migrations.RemoveField(
            model_name="genre",
            name="plays",
        ),
        migrations.AddField(
            model_name="play",
            name="actors",
            field=models.ManyToManyField(
                related_name="actor_plays", to="theatre.actor"
            ),
        ),
        migrations.AddField(
            model_name="play",
            name="genres",
            field=models.ManyToManyField(
                related_name="genre_plays", to="theatre.genre"
            ),
        ),
    ]
